Add signtool.exe search step in manual.yml
Add step to find signtool.exe in the workflow.

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -28,6 +28,18 @@ jobs:
         #shell: pwsh
         #run: choco install -y windows-sdk-10.1
 
+      - name: Find signtool.exe
+        id: find_signtool
+        shell: pwsh
+        run: |
+          $signtool = Get-ChildItem -Path "${Env:ProgramFiles(x86)}\Windows Kits\10\bin" -Recurse -Filter signtool.exe | Select-Object -First 1
+          if (-Not $signtool) {
+            Write-Error "signtool.exe not found!"
+            exit 1
+          }
+          echo "signtool-path=$($signtool.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
+
+
       - name: Build SEA Executable
         uses: bryopsida/node-sea-action@v1
         with:
